// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

[TestFixture]
public class LoginTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }

    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }

    [Test]
    public void RetailerRegister()
    {
        driver.Navigate().GoToUrl("http://localhost:3000/Signup");
        driver.Manage().Window.Size = new System.Drawing.Size(980, 835);
        driver.FindElement(By.Name("name")).Click();
        driver.FindElement(By.Name("name")).SendKeys("Kathirvel");
        Thread.Sleep(1000);
        driver.FindElement(By.Name("email")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.Name("email")).SendKeys("kathirvel23@gmail.com");
        Thread.Sleep(1000);
        driver.FindElement(By.Name("mobilenumber")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.Name("mobilenumber")).SendKeys("8765435678");
        Thread.Sleep(1000);
        driver.FindElement(By.Name("password")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.Name("password")).SendKeys("Sanjai@123");
        Thread.Sleep(1000);
        driver.FindElement(By.Name("shopName")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.Name("shopName")).SendKeys("Kathir store");
        Thread.Sleep(1000);
        driver.FindElement(By.Name("location")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.Name("location")).SendKeys("Tenkasi");
        Thread.Sleep(1000);
        driver.FindElement(By.Name("gstNumber")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.Name("gstNumber")).SendKeys("786543456765");
        Thread.Sleep(1000);
        driver.FindElement(By.CssSelector(".fluid")).Click();
    }

    [Test]
    public void Validlogin()
    {
        driver.Navigate().GoToUrl("http://localhost:3000/");
        driver.Manage().Window.Size = new System.Drawing.Size(980, 835);
        driver.FindElement(By.Name("email")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.Name("email")).SendKeys("arun23@gmail.com");
        Thread.Sleep(1000);
        driver.FindElement(By.Name("password")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.Name("password")).SendKeys("Sanjai@123");
        Thread.Sleep(1000);
        driver.FindElement(By.CssSelector(".fluid")).Click();
    }
    [Test]
    public void Invalidlogin()
    {
        driver.Navigate().GoToUrl("http://localhost:3000/");
        driver.Manage().Window.Size = new System.Drawing.Size(980, 835);
        driver.FindElement(By.Name("email")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.Name("email")).SendKeys("arun767@gmail.com");
        Thread.Sleep(1000);
        driver.FindElement(By.Name("password")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.Name("password")).SendKeys("Sanjais@123");
        Thread.Sleep(1000);
        driver.FindElement(By.CssSelector(".fluid")).Click();
    }

    [Test]
    public void CorrectEmailWrongPassword()
    {
        driver.Navigate().GoToUrl("http://localhost:3000/");
        driver.Manage().Window.Size = new System.Drawing.Size(980, 835);
        driver.FindElement(By.Name("email")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.Name("email")).SendKeys("arun23@gmail.com");
        Thread.Sleep(1000);
        driver.FindElement(By.Name("password")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.Name("password")).SendKeys("Arun@123");
        Thread.Sleep(1000);
        driver.FindElement(By.CssSelector(".fluid")).Click();
    }
}
